version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    container_name: springboot-postgres # Host Address
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: patient_management # Database Name
    ports: 
      - 5000:5432
    networks:
      - internal-net
# spring.datasource.url=jdbc:postgresql://springboot-postgres:5432/patient_management

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    ports:
      - "4001:4001"  # HTTP port
      - "9001:9001"  # gRPC port
    networks:
      - internal-net

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      # Use billing-service as hostname, not localhost
      - billing.service.address.localhost=billing-service
      - billing.service.grpc.port=9001
      # PostgreSQL connection (note: use service name springboot-postgres as host)
      - spring.datasource.url=jdbc:postgresql://springboot-postgres:5432/patient_management
      - spring.datasource.username=myuser
      - spring.datasource.password=mypassword
    depends_on:
      - db
      - billing-service
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
