version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    container_name: springboot-postgres # Host Address
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: patient_management # Database Name
    ports:
      - 5000:5432
    networks:
      - internal-net
  # spring.datasource.url=jdbc:postgresql://springboot-postgres:5432/patient_management

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    image: chamudithaadithya/patient_management_system_billing:latest
    ports:
      - '4001:4001' # HTTP port
      - '9001:9001' # gRPC port
    networks:
      - internal-net
    

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    image: chamudithaadithya/patient_management_system_patient:latest
    # ports:
    # - 4000:4000 NO longer accepts since api-getwat handle it
    environment:
      # Use billing-service as hostname, not localhost
      - BILLING_SERVICE_ADDRESS_LOCALHOST=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
      # PostgreSQL connection (note: use service name springboot-postgres as host)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://springboot-postgres:5432/patient_management
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      # Kafka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db
      - billing-service
    networks:
      - internal-net

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    image: chamudithaadithya/patient_management_system_analytics:latest
    ports:
      - 4002:4002
    depends_on:
      - db
      - billing-service
      - patient-service
    networks:
      - internal-net
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  api-getway:
    build:
      context: ./api-getway
      dockerfile: Dockerfile
    container_name: api-getway
    image: chamudithaadithya/patient_management_system_api_getway:latest
    ports:
      - 4004:4004
    networks:
      - internal-net

# networks:
#   internal-net:
#     driver: bridge

networks:
  internal-net:
    external: true
