name: CICD Pipeline
on: 
  push:
    branches: [main]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports: 
          - 5000:5432
        env:
          POSTGRES_PASSWORD: mypassword
          POSTGRES_USER: myuser
          POSTGRES_DB: patient_management
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5000 -U myuser; do
            echo "Waiting for Postgres..."
            sleep 5
          done

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with: 
          java-version: '21'
          distribution: 'temurin'

      - name: Build project
        working-directory: ./patient-service
        run: mvn clean package --no-transfer-progress 
        
